# Generated by Django 3.0.8 on 2020-07-29 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0002_auto_20200729_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 6, 33, 37, 346599, tzinfo=utc)),
        ),
    ]
