# Generated by Django 3.0.8 on 2020-07-29 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0005_auto_20200729_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 7, 58, 57, 486618, tzinfo=utc)),
        ),
    ]
