# Generated by Django 3.0.8 on 2020-07-31 02:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0012_auto_20200730_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_detail', models.CharField(max_length=50)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Postcategories',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 2, 6, 37, 730, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PostSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
                ('series_detail', models.CharField(max_length=200)),
                ('series_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='yblog.PostCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Postseries',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='yblog.PostCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='yblog.PostSeries', verbose_name='Series'),
        ),
    ]
