# Generated by Django 3.0.8 on 2020-07-31 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0013_auto_20200731_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 2, 8, 29, 310461, tzinfo=utc)),
        ),
    ]
