# Generated by Django 3.0.8 on 2020-07-31 05:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yblog', '0017_auto_20200731_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postseries',
            name='series_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='series',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 5, 30, 25, 704922, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='PostSeries',
        ),
    ]
