# Generated by Django 3.0.8 on 2020-07-31 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0023_auto_20200731_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 7, 7, 6, 946217, tzinfo=utc)),
        ),
    ]
