# Generated by Django 3.0.8 on 2020-08-02 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0029_auto_20200801_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('자료실', (('DS', '알고리즘'), ('AI', '인공지능'), ('APP', '웹앱&모바일앱'), ('CG', '컴퓨터 그래픽스'), ('DB', '데이터베이스'), ('ETC', '기타'))), ('동아리', (('BB', '컴스켓'), ('FB', 'AC잎새'), ('HH', 'YBRO'), ('RM', '소음'))), ('소셜', (('JOB', '채용공고'), ('PJ', '프로젝트'), ('CC', '잡담'), ('Q', '건의')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 15, 16, 10, 611329, tzinfo=utc)),
        ),
    ]
