# Generated by Django 3.0.8 on 2020-08-02 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0031_auto_20200803_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 15, 19, 21, 27683, tzinfo=utc)),
        ),
    ]
