# Generated by Django 2.1.5 on 2020-08-08 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0033_auto_20200806_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 5, 26, 35, 778693, tzinfo=utc)),
        ),
    ]
