# Generated by Django 2.1.5 on 2020-08-10 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0035_auto_20200810_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 14, 19, 23, 627558, tzinfo=utc)),
        ),
    ]
