# Generated by Django 2.1.5 on 2020-08-17 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0043_auto_20200816_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 7, 17, 3, 663618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Study'), (2, 'Clubs'), (3, 'Notice'), (4, 'Social')], max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 7, 17, 3, 662620, tzinfo=utc)),
        ),
    ]
