# Generated by Django 3.0.8 on 2020-08-20 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import yblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0059_auto_20200820_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=yblog.models.path_image_path)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yblog.Post')),
            ],
        ),
    ]
