# Generated by Django 3.0.8 on 2020-08-23 03:08

from django.db import migrations, models
import yblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('yblog', '0060_auto_20200820_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=yblog.models.path_image_path),
        ),
    ]
